authors:
  yongquantan:
    name: Yong Quan Tan
    description: Data & Applied AI Engineer
    avatar: https://avatars.githubusercontent.com/u/52147112?s=400&u=aa71d03e451d455a74674b23259d4e753eb1c020&v=4
    url: https://twitter.com/intent/follow?screen_name=yongquanYQ