authors:
  yongquantan:
    name: Yong Quan Tan
    description: Data & Applied AI Engineer at AMILI
    avatar: https://media.licdn.com/dms/image/v2/D4E03AQEWfE09hBx3PA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1680719543106?e=1749081600&v=beta&t=bVsNHSi-4JF3Wn-PXCIDlnrs0q-EeoUN1q5EXztvv40
    url: https://twitter.com/intent/follow?screen_name=yongquanYQ